// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9mBDrxr-KorWHJW1pqAqDmNjLNsW2T1U',
    appId: '1:537610027188:web:9fb835a47b1d517442d7e1',
    messagingSenderId: '537610027188',
    projectId: 'fir-flutter-codelab-a7523',
    authDomain: 'fir-flutter-codelab-a7523.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-a7523.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzxnZmrrz8wlJfHTQXZ2KrygpaDMkNhp0',
    appId: '1:537610027188:android:db921071cced782042d7e1',
    messagingSenderId: '537610027188',
    projectId: 'fir-flutter-codelab-a7523',
    storageBucket: 'fir-flutter-codelab-a7523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB66lUhtRHELpd4VlvaoEr3sMz-sKX5r-E',
    appId: '1:537610027188:ios:37e0062c6afb7e3742d7e1',
    messagingSenderId: '537610027188',
    projectId: 'fir-flutter-codelab-a7523',
    storageBucket: 'fir-flutter-codelab-a7523.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB66lUhtRHELpd4VlvaoEr3sMz-sKX5r-E',
    appId: '1:537610027188:ios:37e0062c6afb7e3742d7e1',
    messagingSenderId: '537610027188',
    projectId: 'fir-flutter-codelab-a7523',
    storageBucket: 'fir-flutter-codelab-a7523.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
